backend/models/WithdrawPoint.php
<?php

namespace backend\models;

use Yii;

/**
 * This is the model class for table "withdraw_point".
 *
 * @property int $id
 * @property int $user_id
 * @property int $request
 * @property int $balance_on_request
 * @property int $approved -1 = Rejected 0 = Unprocessed 1 = Processed
 * @property string $request_time
 * @property string $approve_time
 * @property string $comment
 * @property int $bank_account_id
 *
 * @property User $user
 */
class WithdrawPoint extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'withdraw_point';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['request'],'checkBalance'],
            [['user_id', 'request', 'balance_on_request', 'approved', 'bank_account_id'], 'integer'],
            [['request_time', 'approve_time','bank_account_id'], 'safe'],
            [['comment'], 'string', 'max' => 200],
            [['approved','balance_on_request'], 'safe'],
            [['user_id'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['user_id' => 'id']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'user_id' => 'User ID',
            'request' => 'Requested Ammount',
            'balance_on_request' => 'Balance On Request',
            'approved' => 'Approved',
            'request_time' => 'Request Time',
            'approve_time' => 'Approve Time',
            'comment' => 'Comment',
            'bank_account_id' => 'Account',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(User::className(), ['id' => 'user_id']);
    }

    public function beforeSave($insert)
    {
        if($this->isNewRecord){
            $this->user_id = Yii::$app->user->id;
            $this->request_time = date("Y-m-d H:i:s");
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    public function checkBalance(){
        if($this->approved == 1 && PointTransaction::myBalance($this->user_id)<$this->request){
            $this->addError('request', "Balance tidak mencukupi");
        }
    }

    public function getBankInfo(){
        return $this->hasOne(BankAccount::className(),['id'=>'bank_account_id']);
    }
}

backend/controllers/WithdrawPointController.php
<?php

namespace backend\controllers;

use Yii;
use backend\models\WithdrawPoint;
use backend\models\WithdrawPointSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use backend\models\PointTransaction;
use backend\models\PointTransactionSearch;

/**
 * WithdrawPointController implements the CRUD actions for WithdrawPoint model.
 */
class WithdrawPointController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all WithdrawPoint models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new WithdrawPointSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionListUnapproved()
    {
        $searchModel = new WithdrawPointSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams, 0);

        return $this->render('list-unapproved', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionListApproved()
    {
        $searchModel = new WithdrawPointSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams, 1);

        return $this->render('list-approved', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionProcess($id){
        $model = $this->findModel($id);
        $model->approve_time = date('Y-m-d H:i:s');
        if($model->load(Yii::$app->request->post()) && $model->save()){
            if($model->approved == 1){
                PointTransaction::reduceBalance($model->user_id, $model->request, $model->comment, 'c', PointTransaction::WITHDRAW);
            }
            return $this->redirect(['withdraw-point/list-unapproved']);
        }
        return $this->render('process', [
            'model' => $model,
        ]);
    }

    public function actionListRejected()
    {
        $searchModel = new WithdrawPointSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams, -1);

        return $this->render('list-rejected', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single WithdrawPoint model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new WithdrawPoint model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        if(!count(Yii::$app->user->identity->bankAccounts)){
            Yii::$app->session->setFlash('isi-bankacc', 'Anda harus mengisi informasi bank terlebih dahulu');
            return $this->redirect(['bank-account/create']);
        }

        $balance = PointTransaction::myBalance(Yii::$app->user->id);

        $model = new WithdrawPoint();
        $model->approved = 0;
        $model->balance_on_request = $balance;

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            Yii::$app->session->setFlash('waiting-approval', "Status penarikan anda akan segera dikabarkan lewat SMS");
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
            'balance' => $balance,
        ]);
    }

    /**
     * Updates an existing WithdrawPoint model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing WithdrawPoint model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the WithdrawPoint model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return WithdrawPoint the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = WithdrawPoint::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

backend/views/withdraw-point/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use nex\chosen\Chosen;

/* @var $this yii\web\View */
/* @var $model backend\models\WithdrawPoint */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="withdraw-point-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'request')->textInput() ?>

    <?= $form->field($model, 'bank_account_id')->textInput() ?>

    <?=
    $form->field($model, 'bank_account_id')->dropDownList(\yii\helpers\ArrayHelper::map(\backend\models\BankAccount::bankAccounts(Yii::$app->user->id),'id','bank.name'));
    ?>

    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/withdraw-point/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model backend\models\WithdrawPointSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="withdraw-point-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'user_id') ?>

    <?= $form->field($model, 'request') ?>

    <?= $form->field($model, 'balance_on_request') ?>

    <?= $form->field($model, 'approved') ?>

    <?php // echo $form->field($model, 'request_time') ?>

    <?php // echo $form->field($model, 'approve_time') ?>

    <?php // echo $form->field($model, 'comment') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/withdraw-point/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model backend\models\WithdrawPoint */

$this->title = 'Create Withdraw Point';
$this->params['breadcrumbs'][] = ['label' => 'Withdraw Points', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="withdraw-point-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/withdraw-point/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel backend\models\WithdrawPointSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Withdraw Points';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="withdraw-point-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?= Html::a('Create Withdraw Point', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'id',
            'user_id',
            'request',
            'balance_on_request',
            'approved',
            //'request_time',
            //'approve_time',
            //'comment',

            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>
</div>

backend/views/withdraw-point/list-approved.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel backend\models\WithdrawPointSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Withdraw Points';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="withdraw-point-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'id',
            'user_id',
            'request',
            'balance_on_request',
            'approved',
            //'request_time',
            //'approve_time',
            //'comment',
        ],
    ]); ?>
</div>

backend/views/withdraw-point/list-rejected.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel backend\models\WithdrawPointSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Withdraw Points';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="withdraw-point-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?= Html::a('Create Withdraw Point', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'id',
            'user_id',
            'request',
            'balance_on_request',
            //'request_time',
            'approve_time',
            'comment',

        ],
    ]); ?>
</div>

backend/views/withdraw-point/list-unapproved.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel backend\models\WithdrawPointSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Withdraw Points';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="withdraw-point-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?= Html::a('Create Withdraw Point', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'id',
            'user_id',
            'request',
            'balance_on_request',
            'approved',
            //'request_time',
            //'approve_time',
            //'comment',

            [
                'class' => 'yii\grid\ActionColumn',
                'template' => '{process}',
                'buttons' => [
                    'process' => function($url, $model){
                        return Html::a("<span class='glyphicon glyphicon-refresh'></span>", $url, [
                            'title' => 'Proses'
                        ]);
                    }
                ],
            ],
        ],
    ]); ?>
</div>

backend/views/withdraw-point/process.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model backend\models\WithdrawPoint */

?>
<div class="withdraw-point-update">

    <h1>Process Withdraw</h1>

    <div class="withdraw-point-form">

        <?php $form = ActiveForm::begin(); ?>

        <p>Request Withdraw Point: <?= $model->request ?></p>
        <p>Request Transfer To: <?= $model->bankInfo->bank->name ?></p>
        <p>Request Transfer To: <?= $model->bankInfo->account_no ?></p>

        <?= $form->errorSummary($model) ?>

        <?= $form->field($model, 'approved')->dropDownList(['1'=>'Approved', '-1' => 'Reject']) ?>
        <?= $form->field($model, 'comment')->textInput() ?>

        <div class="form-group">
            <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
        </div>

        <?php ActiveForm::end(); ?>

    </div>

</div>

backend/views/withdraw-point/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model backend\models\WithdrawPoint */

$this->title = 'Update Withdraw Point: {nameAttribute}';
$this->params['breadcrumbs'][] = ['label' => 'Withdraw Points', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="withdraw-point-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/withdraw-point/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model backend\models\WithdrawPoint */

$this->title = $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Withdraw Points', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="withdraw-point-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'user_id',
            'request',
            'balance_on_request',
            'approved',
            'request_time',
            'approve_time',
            'comment',
        ],
    ]) ?>

</div>